radiocosmology/caput

- caput/config.py
- caput/mpidataset.py
- scripts/caput-pipeline
Two main items in here required for the latest pass0 pipeline. The mpidataset stuff will mostly get supplanted when the parallel memh5 gets there, but it's needed for now.
> Extended mpidataset and finalise config support

- caput/memh5.py
A few small fixes to `memh5` to help compatibility with pipeline code. Notably the `__new__` method was removed from `MemDiskGroup` with the relevant parts moved to `__init__` or into a new `from_group` method. Also a few fixes to the `comm` attribute.
> Small memh5 fixes

- caput/memh5.py
- caput/mpiarray.py
- caput/mpiutil.py
- caput/tests/test_memh5_parallel.py
- caput/tests/test_mpiarray.py
Some work to make the package also work when there is no MPI, so it can work either parallel or serial. May not be very useful.
> Make the package work when there is no MPI

- setup.py
> small fix to setup.py

- .travis.yml
- caput/pipeline.py
- setup.py
Simple fix for a porting problem in the pipeline code. Also, hopefully hacked a fix in for the failing unit tests.
> Porting bug fix

- caput/mpiarray.py
- caput/tests/test_mpiarray.py
This is useful as it may allow you to use a more appropriate axis for the read, which can be useful when the dataset is chunked.
> Allow read to be distributed along specified axis

- caput/misc.py
- caput/pipeline.py
- caput/tests/test_misc.py
A context manager for wrapping around file creation operations that
automates the creation and cleaning of lock files, as well as removal of
the temporary file when there is a failure.
> Context manager for lockfiles

- caput/mpiarray.py
h5py has an issue where it will fail for collective operations where a
rank performs a zero length selection (h5py #965), this works around it
by turning off collective IO if that would happen.
> fix: workaround for h5py collective IO bug

- caput/memh5.py
- caput/mpiarray.py
I finished up adding support for chunks/compression to `MPIarray`s last week. I tried to mimick how these options are passed in `h5py`.
I've tested this in the pipeline with writing out a `SiderealStream` and it seems to work as expected.
One thing to note is that collective IO is required to do chunked writes, so I've had to mess around a bit with the logic that figures out when to use this.
I also have not done any performance testing. This is obviously going to be important, but I know Richard has been investigating this in previous code updates, so I thought I would start the pull request and get some input on how to test it, what to compare it too.
I'm going to open a separate PR in `draco` with updates to the containers that make use of chunking/compression.
> Chunked HDF5 with MPI

- caput/scripts/runner.py
It seems runner is missing the call to group at the end of file?
> fix(runner): Add call to group at end of file.

- .travis.yml
- caput/memh5.py
- caput/pipeline.py
- caput/tests/test_metadata.py
- version strings for list of modules
- config dump
Closes #104
> feat(Manager): add metadata options

- caput/memh5.py
- caput/tests/test_memh5.py
I think this is nicer, but not sure if you agree.
> memh5: let json.JsonEncoder.default raise the TypeError

- caput/memh5.py
- caput/tests/test_memh5.py
add_history previously accepted single-level dictionaries only and they
were added as attributes to the history group. This was a simply
solution to dictionary de-/serialization with json). Now that we support
full de-/serialization of dictionaries using json, the history feature
was ~broken~ not broken, but produced fully serialized dicts below the first level, which is a bit weird. To make it usable again, the history is now not a group
anymore, but an attribute, so that dictionaries of any depth can be
added.
Reading the old history format is still supported but creates a
deprecation warning.
> feat(BasicCont): make history an h5 attribute

- caput/memh5.py
Some old data format may have numpy.ndarray's in history["acq"]. To be
able to write these (for backwards compatibility) we need to add a json
decoder for numpy.ndarray. Note that reading the files again will show
list's instead of ndarray's.
Closes #131
> fix(memh5): json serialize numpy ndarray

- caput/memh5.py
The previous implementation caused a reference cycle to be generated preventing the entire container from being automatically freed. The way this happens is quite interesting, at least to me...
- Because of the way python late binds closures, as soon as `.redistribute` is called, the recursive inner function `_tree_crawl` forms a self referencing cycle (via an internal cell object). This reference cycle prevents it being automatically freed when the parent container object's external reference is removed.
- Unfortunately on top of this, the use of `self.comm.rank` binds a reference to `self` into the cyclic closure and means that even when all external references to the container are gone, this cyclic closure still holds one and thus the parent container itself cannot be freed either. …
> fix(memh5): modify BasicCont.redistribute to prevent reference cycles

- caput/memh5.py
The caput side of radiocosmology/draco#100
> fix(memh5): change _make_selections to be a classmethod

- caput/config.py
- caput/memh5.py
- caput/mpiutil.py
- caput/pipeline.py
- caput/time.py
- caput/tod.py
This change allows direct control over task construction and
configuration, and allows injection and inspection of pipeline products,
and is aimed to help with prototyping and debugging of pipelines.
> feat(pipeline): allow construction and control of pure Python pipelines

- caput/tests/test_moving_weighted_median.py
- caput/weighted_median.pyx
This moves to using a weighted quickselect algorithm for calculating the
*static* weighted median which is significantly faster (> 50x) than the
original AVL tree code.
> perf(weighted_median): use quickselect to calculate the static median

- caput/misc.py
- caput/tests/test_time.py
- caput/time.py
- requirements.txt
This is the start of a refactoring of all the ephemeris code.
> Skyfield refactor and transit/rise/set time routines

- .github/workflows/main.yml
- caput/memh5.py
- caput/mpiarray.py
- caput/pipeline.py
- caput/tests/test_memh5.py
- caput/tests/test_moving_weighted_median.py
- pylint-ignore.md
pylint 2.7.0 brought us new warnings
- fix those warnings
- fix pylint version
> Fix pylint to version 2.7.0 and fix new warnings from that version

- caput/memh5.py
If hints are enabled, then the axis that each dataset is
distributed over at the time it is written to disk will be
saved to that dataset's attributes.  The dataset will then
be distributed over that axis the next time it is read from disk.
> feat(memh5): add a __memh5_distributed_axis hint

- caput/config.py
- caput/mpiutil.py
- caput/scripts/runner.py
- fix(config): format string bugs
- feat(template-run): add option to submit templat jobs to the queue
- feat(runner,mpiutil): allow control of MPI abort on exception
> Useful enhancements for running the pipeline

- caput/interferometry.py
- caput/mpiarray.py
- caput/pfb.py
- caput/scripts/runner.py
- doc/requirements.txt
This also changes the default setting to *disallow* overwrites.
This adds yet another feature to runner.py which is become a big mess. We probably need to do a big cleanup of it.
> feat(runner): add an option to control overwritiing old pipeline runs

- caput/memh5.py
Needed because of https://github.com/mpi4py/mpi4py/issues/177.
Shift-Bcasted arrays with little or big endian byteorders will result in
an exception.
Is it ever possible that the endian set does not match the architecture? What do we do in that case?
If we use an upgraded version of mpi4py, this PR is not needed.
> fix(memh5): ensure contained numpy arrays have a native dtype.byteorder

- caput/mpiarray.py
- caput/tests/test_mpiarray.py
…ssed through to the underlying numpy.copy call
> fix `np.median` error with MPIArray

- caput/memh5.py
- caput/mpiarray.py
The previous code assumed that lists coming from attributes would be
returned as numpy arrays, but this is specific to h5py.
> fix(memh5): issue with distribution of zarr datasets

- caput/time.py
- caput/tools.py
Also add a helper method for getting unique values from a list while maintaining order. This should be pretty fast without relying on numpy
> Observer property to get current LSD/CSD

- caput/pipeline.py
> fix(pipeline): remove erroneous compression options that caused a crash

- caput/mpiarray.py
- caput/tests/test_mpiarray.py
- test(mpiarray): check more complex reshapes
- doc(mpiarray): fix docstring argument order
- fix(mpiarray): ensure reshape works properly
> MPIArray reshape fixes

- .readthedocs.yml
- caput/mpiarray.py
- doc/requirements.txt
Also, fix the buildthedocs setup
> feat(mpiarray): helper function to apply a selection to an array

- .gitignore
- .readthedocs.yml
- caput/cache.py
- caput/config.py
- caput/fileformats.py
- caput/memh5.py
- caput/mpiarray.py
- caput/mpiutil.py
- caput/pipeline.py
- caput/profile.py
- caput/scripts/runner.py
- caput/time.py
- caput/tod.py
- caput/tools.py
- pyproject.toml
see radiocosmology/draco#243 for details on rules
> Extra ruff rules

- caput/config.py
Right now the output is something like 
```
UserWarning: Property <caput.config.Property object at 0x14d8eb2ae580> is deprecated and may behave unpredictably.
```
which isn't very helpful. We should at least try to tell the user something about the name of the property.
Unfortunately, with the way that `config.Property` is typically used, the key won't get set until the first time that `__get__` or `__set__` is called. This just means that if someone is deprecating a property, they should also provide an argument for `key` when they set `deprecated=True`.
Or, we could delay this warning until the first time `__get__` or `__set__` is called. Thoughts?
> Try to warn user about specific key in deprecation warning

- caput/config.py
The last change generally worked, except that it would emit a warning when linting a config file since all properties were checked, even those that weren't set. This fixes that, so now you'll only get a warning when linting if you're actually setting the property in your config file.
> Make sure deprecation warning doesn't show up when loading from config unless the property is set
