radiocosmology/caput

caput/memh5.py
caput/tests/test_memh5.py

This addresses #16. MemGroup.create_dataset can now take either a
relative or absolute path as the name such that the dataset can be
created in an different group from the calling group.

Memh5 dataset creation in other groups.

---

caput/time.py
requirements.txt
setup.py

Caput will now initially try and install the skyfield when the package installs. It will also now use attempt to update the data when it is first used and otherwise use existing data.

Improvements to how skyfield data is treated

---

scripts/caput-pipeline

- New mandatory yaml parameter: `cluster' can be `gpc' or `cedar' 
- New optional parameters: `mem' defaults to `128000M', `account' defaults to `rpp-krs'
- `ppn' now has two defaults, 8 on gpc and 32 on cedar

Added support for Cedar

---

caput/config.py

Modify config.Reader to raise exceptions if there are discrepancies between keys in the configuration dictionary and Properties

config key exceptions

---

caput/pipeline.py
caput/tod.py

This fixes two bugs.  The first is just a `type() is list` comparison that no longer works in newer versions of python.
The second occurs when concatenating distributed datasets that I think may have been introduced in [4343059](https://github.com/radiocosmology/caput/commit/434305988e4e4260be19320080f596efe22e8204#diff-b295d0d06e0d6df9609f55b50997befc).
Applying the time slice to `dataset` converts it from an instance of `MemDataset` to either an `MPIArray` or `np.ndarray`.
For distributed datasets, this causes the `isinstance(dataset, memh5.MemDatasetDistributed)` condition to fail, and the output dataset is initialized as non-distributed.
The proposed fix converts back to either `MemDatasetCommon` or `MemDatasetDistributed` after applying the time slice.  It determines which one to use …

Concat dist bugfix

---

caput/memh5.py
caput/tests/test_memh5.py

Here are two changes that fix cyclic references and garbage collection.
Changing `MemDataset._storage_root` to a weak reference fixes what I think is the last remaining cyclic reference. I found this using the excellent `objgraph` package. It is as simple as `import objgraph; objgraph.show_refs(data, filename='sample-graph.png')`.
The second is less backward compatible: it removes automatic file closure. This is more inline with how h5py closes files. More importantly, @rmck1 found the following in the python docs: "Objects that have del() methods and are part of a reference cycle cause the entire reference cycle to be uncollectable.", so the existence of __del__ makes the whole container less robust to memory leaks. Seems like a good idea to get rid of it.
Thanks @rmck1 for figuring most …

Fix cyclic references

---

CHANGELOG.md
caput/memh5.py
caput/misc.py
caput/mpiarray.py
caput/tests/test_memh5_parallel.py

Uses HDF5/h5py parallel features to allow concurrent writing of datasets and
more efficient reading.
I have noticed some slight issues using h5py collective parallel routines in
test examples when using OMPIO is the MPI-IO implementation (ROMIO did not seem
to have this problem). At the moment I'm still investigating. When cedar comes
back I'll try to test whether this is a reasonable concern.

Parallel container IO using h5py and MPI

---

caput/mpiarray.py
caput/tests/test_mpiarray.py

Instead of receiving blocks in-place, this creates a numpy array for each block, that is then copied into the new local array. This is because slicing by indexes for the local array on a variable axis does not result in a contiguous array accepted by `mpi4py.MPI.Recv`. Suggestions are welcome!
#43

rewrite MPIArray redistribute without transpose_blocks

---

caput/misc.py
caput/mpiarray.py

This includes a large refactoring of the mpiarray IO code to break it up
and add the ability to split IO into a chunks to ensure that they fit
within HDF5's limits. Additionally collective IO is turned off for
writes along axis=0, and parallel IO entirely for reads along axis=0 to
improve IO performance.

fix: partition parallel IO to be under the 2GB HDF5 limit

---

caput/memh5.py

All metadata changing operations in HDF5 need to be done collectively
(when in MPI mode). This means that datasets must be created in the same
order, by sorting the keys when copying to/from HDF5 we can guarantee
this happens.

fix(memh5): sort items when copying to/from HDF5 to eliminate MPI errors

---

pyproject.toml
requirements.txt
setup.py

If we really need to maintain three different lists of requirements, let's at least make them all the same.
`numpy-1.16` has a forwards-incompatible ABI change which seems to be causing grief (see numpy/numpy#12785), but if we enforce a NumPy after the change, we should be good, hopefully.
Closes #87

build: Enforce numpy>=1.16 everywhere

---

.gitignore
.travis.yml

The contents of doc/requirements.txt are not typically installed when caput is deployed.  We should remove it from the blanket install rules to avoid masking missing items in ./requirements.txt which happen to be listed in doc/requirements.txt.

ci: move installing doc/reauirements.txt to docbuild check

---

caput/scripts/runner.py

Sajan ran into an issue running the holography pipeline where it would fail to copy the config file to the job directory because of permissions, even though he had group write access to the directory and file. This is because there was an existing config file there owned by my user, and `shutil.copy` modifies file metadata as well as contents. This is not allowed on a file owned by another user. Using `shutil.copyfile` should resolve this.

Use copyfile instead of copy

---

caput/pipeline.py

A property of misc.getfullargspec was misspelled, I renamed following the suggestion of @jrs65

Bug fixed on variable name: pro_argspec.keywords to pro_argspec.varkw

---

caput/tod.py

Fixes bug in `_copy_non_time_data` where the `data` variable
was being over written if a dataset without a time axis was
encountered.
Bug introduced in commit 249face8d4e0ab38e91507c0724606687d8515c8.

fix(tod): fixes bug where `data` variable overwritten

---

caput/memh5.py
caput/tod.py

This commit changes the default setting for converting HDF5 attribute
strings when loading/saving memh5 containers to be backwards
compatibility with older FRB code.
I don't think this should have any effect on cosmology code as we override the default setting upstream anyway.

fix(memh5): change default `convert_attribute_strings` for backwards compatibility

---

caput/time.py

The documentation for caput.time.SkyfieldWrapper says that
default expire is False, but the init function had
expire=True.

fix(time): set SkyfieldWrapper default expire=False

---

caput/config.py
caput/pipeline.py
caput/scripts/runner.py
doc/config.rst
doc/index.rst

- Allow to pass a dict to config section 'pipeline/logging' that defines a
log level per module.
- Add option 'logging' to task config that defines the loglevel for the
module the task uses (takes priority over the above).
Fixes https://github.com/chime-experiment/Pipeline/issues/36

feat(pipeline): improve log level config

---

.github/workflows/main.yml
caput/mpiarray.py
caput/tests/test_selection.py
caput/tests/test_selection_parallel.py

Currently MPIArray.from_hdf5 uses the shape of the post-selection dataset
to form each nodes selection.  This results in reading in the wrong
data from disk for distributed datasets.  The fix uses the shape of the
dataset pre-selection.

fix(mpiarray): bug when selecting data during distributed read

---

caput/misc.py
caput/pipeline.py

This changes the behavior of `misc.lock_file()` to match its docstring: specifically, if no `comm` argument is specified, the file is opened and closed by the current rank, while if `comm` is specified, only rank 0 does the opening and closing.
I searched for `lock_file` in the relevant repos in radiocosmology and chime-experiment, and the only place where `lock_file()` is actually used is in `caput.pipeline`, and I modified the relevant call to specify a `comm` argument so that the previous behavior is preserved.

Fix lock_file() behavior

---

caput/tests/test_time.py
caput/time.py

If `step` is not provided, `transit_times` will use a default initial search step of one fifth of the search interval, or 0.2 days, whichever is smaller.
Also:
- raises `ValueError` if the initial search step is larger than the search interval, in which case no transit will ever be found.
- raises `ValueError` if the search interval is non-positive. Without this, `NumPy` instead raises `ValueError` with a cryptic message complaining about negative array length)
Closes #149

fix(transit_times): Handle small intervals better

---

caput/config.py
caput/pipeline.py
caput/scripts/runner.py
caput/tests/test_config.py
caput/tests/test_lint.py
caput/tests/test_metadata.py

**Value of `requires` has no corresponding `out`:**
```
pipeline:
tasks:
- in: input_files
out: siderealday
type: caput.tests.test_lint.DoNothing
- in: siderealday
out: tstream
params:
a_list:
- 1
requires: input_files
type: caput.tests.test_lint.DoNothing2
```
output:
```
caput.pipeline.PipelineConfigError: Setting up task 0 caused an error - Value 'in' for task <class 'caput.tests.test_lint.DoNothing'> has no corresponding 'out' from another task (Value input_files is not in []).
```
**Input file doesn't exist:**
```
pipeline:
tasks:
- out: input_files
params:
files: /this/does/not/exist.h5
type: draco.core.io.LoadFilesFromParams
- in: input_files
out: siderealday
type: ch_pipeline.analysis.sidereal.SiderealGrouper
- in: siderealday
out: maskedday
params:
output_name: rfi_filtered.h5 …
```

Pipeline script linting

---

caput/time.py

Use the sidereal second to set the end time to one sidereal day
later if not specified. Otherwise you get two transit times if
t0 is within a few minutes of transit.
This seemed like unexpected behaviour to me.

fix(time.Observer.transit_times): Use sidereal day.

---

caput/pipeline.py
caput/scripts/runner.py

Fix linter

---

caput/pipeline.py

PipelineConfigError was removed in 8f22399 but was still used outside of
caput. This adds a deprecated version.
BREAKING CHANGE: caput.pipeline.PipelineConfigError is deprecated and
will be removed in July 2021. Use caput.config.CaputConfigError instead.
Closes #155

chore(pipeline): add deprecated PipelineConfigError

---

caput/scripts/runner.py

Fixes some problems introduced by previous pathlib commit:
- expandpath would raise an exception if path doesn't exist,
breaking with previous behaviour.
- mkdir call for job directory didn't create parent path
- use of + with PosixPath
I didn't exhaustively audit that commit. I only fixed things until I could get `chp item generate` to work again.

fix(scripts.runner): Broken pathlib usage.

---

caput/mpiutil.py
caput/pipeline.py
caput/tests/conftest.py
caput/tests/test_pipeline.py
caput/tests/test_time.py
caput/time.py

~Set up in, out and requires keys in constructor instead of in Manager.add_task.~
Do validation of special keys in `validate()`, instead of in constructor
Closes #148

fix(OneAndAone): move validation to special function

---

caput/config.py
caput/scripts/runner.py

This is a bit of a hack at the moment, but is a first attempt at some functionality I'd like to be in the pipeline. I've been using it to run grids of test jobs like this:
```bash
$ caput-pipeline template-run --var nside=128,256,512 --var redshift=10,30 testconv_za.yaml.tmpl
```
and the `.tmpl` file contains things like:
```yaml
- type: draco.core.io.LoadBasicCont
out: lss
params:
files:
- lss_n{nside}.h5
- type: cora.signal.lss.GenerateConstantBias
in: lss
out: biased
params:
bias: 0.0
lightcone: false
redshift: {redshift}
output_name: bf_n{nside}_z{redshift}.h5
save: true
```

Allow variable substitution into pipeline scripts

---

.github/workflows/main.yml
caput/misc.py
caput/pipeline.py
caput/profile.py
caput/scripts/runner.py
caput/tests/conftest.py
caput/tests/test_pipeline.py
caput/tests/test_psutilprofiler.py
caput/time.py
caput/weighted_median.pyx
setup.py

To turn on profiling with psutil, pass the flag `--psutil` with pipeline `queue` or `run`.
The profiling results will be saved to csv files, one for each rank, in the pipeline's `work_dir` as `perf_{rank}.csv`.

feat(runner): add psutil based profiling to caput-pipeline

---

caput/mpiarray.py

When following the code-threads for [this issue](https://github.com/radiocosmology/caput/issues/186), it became clear that `MPIArray` never asserts that the `global_shape` it receives is a tuple, when initially creating an `MPIArray`. This could result in [problems](https://github.com/radiocosmology/caput/issues/186), when referencing a container `dataset`, since they pull the `MemDatasetDistributed`'s `shape` from its `MPIArray's` `_global_shape`.
We may want to add `typing` information to `MPIArray`, opening PR to see if we want to do that.
At the moment, I still did not know who is changing the `tuple shape` from the original container's dataset, to the `list shape` in the `containers.empty_like` container.

fix(mpiarray): ensure global_shape for new MPIArray is a tuple

---

caput/pfb.py

Don't know why this didn't get merged a long time ago -- based on Richard's suggestion here:
https://github.com/radiocosmology/caput/issues/173

Remove Nyquist frequency from PFB

---

.github/workflows/main.yml
caput/config.py
caput/fileformats.py
caput/memh5.py
caput/misc.py
caput/mpiarray.py
caput/pipeline.py
caput/profile.py
caput/tests/conftest.py
caput/tests/test_lint.py
caput/tests/test_memh5.py
caput/tests/test_memh5_parallel.py
caput/tests/test_mpiarray.py
caput/tests/test_selection.py
caput/tests/test_selection_parallel.py
caput/tests/test_truncate.py
caput/tod.py
caput/truncate.hpp
caput/truncate.pyx
doc/conf.py
doc/requirements.txt
requirements.txt
setup.py

TODO:
Also see https://github.com/radiocosmology/draco/pull/130
and chime-experiment/ch_pipeline#82
Closes https://github.com/chime-experiment/Pipeline/issues/33
**Edit by @anjakefala**
As of 2021-08-23, here is the discussed remaining work for this PR, along with any unchecked boxes above:
- Update: ch_util actually pushes the docs to github pages, not readthedocs: https://github.com/chime-experiment/ch_util/pull/10

feat(memh5): zarr support

---

caput/mpiarray.py
caput/tests/test_mpiarray.py

If used with draco, requires: https://github.com/radiocosmology/draco/pull/125
`view(MPIArray)` -> `__array_finalize__`
`MPIArray[slice]` -> `__getitem__` -> `__array_finalize__`
`MPIArray()` -> `__new__` -> `__array_finalize__`
ufuncs are the universal functions that are applied element by element in nparrays. Such a `np.add()`, `np.multiply()`. If they end up summing over an axis, they are a ufunc with a `reduce` method. If they go element-by-element, they are a ufunc with an `outer` method. If they occur in-place, they have an `at` method.
ufunc -> `__array_ufunc__`
More links on the role all these various functions play in writing subclasses for NumPy arrays can be found here: https://github.com/chime-experiment/Pipeline/issues/81
The new `AxisException` will be added. It will be …

feat(mpiarray): ufunc, __array_finalize__, and  __getitem__ handling for MPIArray

---

caput/mpiarray.py

This PR cleans up the logic around how the writing code decides whether to use collective IO or not, and then only warns for unexpected cases.

fix(mpiarray): only give warning when compression is disabled by the pipeline

---

caput/mpiarray.py

Although this should be fixed everywhere in the pipeline at the moment, it is not very clear that the actual error that ends up getting thrown is caused by this specifically. This check might help us in the future by making it clear what is going on.

Add explicit TypeError when ufunc tries to output to a numpy array

---

caput/tod.py

I'm putting this one in separately as it's currently breaking all of ch_utils tests.
There were two main issues in here:
- The newly refactored method was trying to access the `.data` attribute, but that's not available when copying an `h5py.Dataset`. Switching to `[:]` should be equivalent, albeit a little slower for the `MemDataset`'s.
- `h5py` returns attributes as bytestrings as so the lookup for time axes was failing as we pass them in as unicode strings. This explicitly converts the strings from the dataset.

fix(tod): issues copying data from h5py datasets

---

.github/workflows/main.yml
caput/memh5.py
caput/mpiarray.py
caput/tests/test_mpiarray.py
caput/tests/test_selection_parallel.py
requirements.txt
setup.py

- test(mpiarray): tests actually cover __call__ ufuncs not outer ones
- test(mpiarray): check reductions over multiple axes
- test(mpiarray): increase test coverage
- fix(mpiarray): address ufunc corner cases and remove unncessary MPI calls

MPIArray cleanups and speedups

---

caput/mpiarray.py

Reduce memory usage and remove an extra step from `redistribute`. This offers some performance improvements when the number of ranks is small but MPI overhead dominates at larger scales.

perf(MPIArray): Write redistributed chunks directly into target array

---

.github/workflows/main.yml
setup.py

`numcodecs 0.7.3` uses a version of `py-cpuinfo` that does not support Apple Silicon. Newer versions of `numcodecs` don't have this issue, so if possible, we should not pin to 0.7.3.

build(setup.py, .github/workflows/main.yml): un-pin numcodecs version

---

caput/weighted_median.pyx

Based on the way _mwm_2D moves over the array, the performance is significantly better if the 0th window size is larger than the 1st window size. 
Also, let `moving_weighted_median` accept any real numeric array

perf(moving_weighted_median): transpose 2D array if window size [0] is less than size[1]

---

caput/_fast_tools.pyx
caput/tools.py
caput/tools.pyx
setup.py

Multiple versions of `_invert_no_zero` existed, with a faster cython version existing in `draco`. Since `draco` is not a dependency everywhere, this PR would move `_invert_no_zero` into `caput`. 
Accompanying PRs:
radiocosmology/draco#202
chime-experiment/ch_util#41

Move cython `_invert_no_zero` into `caput`

---

.gitignore

Add directory `caput/data/` to gitignore. It is marked as untracked by git due to the following files, which are automatically downloaded by some routines in the `time` module:
```
caput/data/de421.bsp
caput/data/finals2000A.all
caput/data/Leap_Second.dat
```

Add data directory to gitignore

---

caput/mpiarray.py
caput/mpiutil.py
caput/tests/test_mpiarray.py

Modifies `MPIArray.redistribute` method to reduce overall memory use. This is accomplished by passing messages cyclically to the `i` adjacent neighbour for `i` total ranks, letting us use only one send and one receive buffer at a time.

Reduce memory used by `MPIArray.redistribute`

---

caput/memh5.py
caput/tests/test_memh5.py
caput/tests/test_memh5_parallel.py
caput/tests/test_tools.py
caput/tools.py

This PR provides `.copy` methods for `MemDataset` and `MemDiskGroup` classes. 
`MemDataset.copy` can optionally do a deep or shallow copy (deep is default) and set the memory layout of the underlying data (if it is a numpy array). By default, this is the same layout as the dataset being copied. 
`MemDiskGroup.copy` deep copies all datasets by default and provides a `shared` argument. This is implemented via the `deep_group_copy` method, which is extended to optionally deep copy datasets (except those that are shared) and copy distributed arrays __only__ in the memory -> memory case. I made considerations based on discussion in #190. 
This PR also provides a a tool to check two objects which may contain numpy arrays for equality (ex: a list of arrays, dict with array arguments, etc...). …

Provide `.copy` methods for `MemDataset` and `MemDiskGroup`

---

caput/config.py

Setting a task `output_format` config property fails if given anything except `h5py` or `zarr`. This change allows the `output_format` config to be set by a `fileformats.FileFormat` subclass (`H5PY` or `Zarr`).
I should maybe take a deeper dive into this, because it actually shouldn't have been hitting the `val = val.lower()` call anyway...

Allow fileformat to be set by fileformat subclass

---

caput/tests/test_tools.py

The `invert_no_zero` method was moved awhile back, but the tests didn't get moved along with it.

Move invert_no_zero testing from draco repo

---

.github/workflows/main.yml
caput/__init__.py
caput/cache.py
caput/config.py
caput/fileformats.py
caput/interferometry.py
caput/memh5.py
caput/misc.py
caput/mpiarray.py
caput/mpiutil.py
caput/pfb.py
caput/pipeline.py
caput/profile.py
caput/scripts/__init__.py
caput/scripts/runner.py
caput/tests/__init__.py
caput/tests/conftest.py
caput/tests/test_config.py
caput/tests/test_mpiarray.py
caput/time.py
caput/tod.py
caput/tools.py
pyproject.toml

This PR adds some additional linting to the CI pipeline, including:
- ~~pydocstyle (docstring formatting from PEP 257)~~
- ~~flake8: add E266 check (multiple hashes to start a comment)~~
- Use [ruff](https://github.com/charliermarsh/ruff) for linting, including flake8 and pydocstyle errors
- Remove "ignore" for E266, E203, W503
It also fixes all existing docstring issues in this repo, ignoring the "tests" directory.
Ignore the following pydocstyle errors:
- D105: Missing docstring in magic method
- D107: Missing docstring in __init__
- D203: 1 blank line required before class docstring
- D213: Multi-line docstring summary should start at the second line
- D400: First line should end with a period _(only ignoring this because there's another error that catches the same thing)_
- D401: …

Use ruff for CI linting 

---

caput/memh5.py
caput/tests/test_tod.py
caput/tod.py

This PR provides access to the `attrs` dict of each `index_map` container in a dataset, through a new property called `.index_attrs`. This is to allow us to set custom behaviour for any axis (such as alignment in time).
The proposed convention allows alignment to only be [-1, 0, 1], with 1 corresponding to a left-alignment index, -1 corresponding to a right-aligned index, and 0 a centred index. I'm open to changing this if an argument is made against it.
Related PRs:
- https://github.com/chime-experiment/ch_util/pull/52
- https://github.com/chime-experiment/ch_pipeline/pull/168
- https://github.com/radiocosmology/draco/pull/227

Timstamp Alignment (1/4): Add `index_attrs` property to `BasicCont` to access attrs of index maps

---

caput/time.py
caput/truncate.pyx
caput/weighted_median.pyx
requirements.txt

This PR should address two things:
- Moving distutil directives to the top of the files so they compile properly (#244 #245 )
- Pinning a maximum numpy version 1.24. Numpy 1.25 seems to change some things under the hood with certain ufuncs which can cause unexpected behaviour with mpiarray, so we should review these changes and make any necessary changes before supporting numpy 1.25 (#247). We don't actually use numpy > 1.24 anywhere, so this should be ok for the time being

fix(pyx): ensure distutil directives are read and pin max numpy version 

---

caput/scripts/runner.py

Before a job is submitted mpi4py modifies the environment in
a way that is invisible to Python. This modified environment is
inherited by the submitted jobs and was causing them to crash. This
change resets the environment for the subprocess that submits that job.

fix(runner): reset the environment to stop crash at job start

---

caput/tests/test_mpiarray.py
requirements.txt

- test(mpiarray): check that median works with numpy >= 1.25
- chore: remove pin from numpy version

fix numpy median

---

caput/scripts/runner.py

This adds command-line options to `caput-pipeline` to get slurm or PBS to email a specific address when certain job events take place (e.g. begin, fail), inheriting the options from each scheduling system. I've only tested it on slurm (cedar), but the PBS syntax seems simple enough that it should work as well...

Add email notification options for batch jobs

---

.github/workflows/main.yml
.readthedocs.yml
caput/__init__.py
caput/cache.py
caput/config.py
caput/fileformats.py
caput/interferometry.py
caput/memh5.py
caput/misc.py
caput/mpiarray.py
caput/scripts/runner.py
caput/tests/test_memh5.py
caput/tests/test_memh5_parallel.py
caput/tests/test_mpiarray.py
caput/tests/test_pipeline.py
caput/tests/test_selection.py
caput/tests/test_selection_parallel.py
caput/time.py
caput/tod.py
pyproject.toml

- feat hints to override
- fix(memh5): error with distributed loading of files with datasets in groups
- ffirst
- refactor(memh5): move no selections sentinel to empty list to simplify

parallel load with no attributes

---

caput/config.py
caput/memh5.py
caput/mpiarray.py
caput/mpiutil.py
caput/pipeline.py
caput/profile.py
caput/scripts/runner.py
caput/tod.py
pyproject.toml

Enforce linting rule RUF012

---

caput/mpiarray.py

This is relevant because of the check for available memory. If we are on a single node, we don't need to make a new array, so this was effectively limiting users to mpiarrays that were < ~0.4 of the available memory (which could be problematic in a notebook, for example)

Avoid redistribute copy if using a single mpi process

---

caput/pipeline.py
caput/scripts/runner.py

Add a `--force` flag to `module purge` and add a `module use` option to pipeline runner.
Also remove deprecated `system_packages` from `.readthedocs.yml`. see https://blog.readthedocs.com/drop-support-system-packages/

Runner: module force purge and module use

---

caput/pipeline.py
caput/profile.py
caput/tools.py

This is a pretty involved PR, so it may take some time to review.
This PR addresses most of the issues in #181 and #152. In particular:
- The pipeline runner uses a priority system to choose the next task to run, based on
- Number of times a task can run and its net consumption per iteration
- Base priority as set by the user
- Pipeline config order
- A task which is a pure producer (i.e. has no input keys) will _never_ be `available`, meaning that these will *only* run when nothing else is able to do anything
- A task will not be able to run `next` if `setup` did not run successfully
- Separate the selection of task to run next from the main run loop, which makes it easier to implement different task selection methods
- Include a `legacy` option which will mimic the current pipeline …

Pipeline runner improvements

---

requirements.txt

At the moment, there are no available bitshuffle wheels built for `numpy>=2`. Also, our `weighted_median` module has some compatibility issues with `numpy >= 2`. For now I've just pinned `numpy < 2` until I can figure out these incompatibilities

Pin numpy < 2

---

.github/workflows/main.yml
caput/mpiarray.py
caput/tod.py
caput/tools.py
pyproject.toml
setup.py

Python 3.8 will reach end-of-life in October 2024, so we should increase the minimum supported version

Increase minimum python to 3.9

---

caput/pipeline.py

If a task receives the same key input for both `setup` and `process` methods, only `setup` would receive the input and `process` would eventually fail.
I still have a job running to validate this works, but it seems pretty straightforward

llow a task to receive the same input for setup and process method

---

caput/interferometry.py
caput/tests/test_interferometry.py
caput/tools.py

This imports two general-purpose angle-related functions from other modules using caput, with the intention of re-exporting them back to those modules:
* `rotate_ypr`: rotates a 3-basis by a yaw, pitch, and roll. Originally from drifscan: https://github.com/radiocosmology/driftscan/blob/8def16f7d1f9d35f729305dd8998c40a7cb7aceb/drift/telescope/cylbeam.py#L44
* `sphdist`: calculates the angular distance betwee two points on the sphere.  Originally from ch_util: https://github.com/chime-experiment/ch_util/blob/c460b37b27f5bcaa1dfbe7897f3ade88e6e6775b/ch_util/ephemeris.py#L358
I have made some minor changes to the docstrings.  There are also some very rudimentary unit tests.

feat(interferometry): Import from ch_util and driftscan

---

caput/time.py

The skyfield documentation is poor, but I think the intention is that the `Star.names` attribute is meant to be iterable.  The skyfield code doesn't reference `Star.names` at all, and there's no documentation on the meaning of the attribute (or any of the parameters of `Star.__init__`), so it's very much unclear.
The default value for `Star.names` is an empty tuple.  Probably any (non-`str`) iterable would be reasonable.
This changes `skyfield_star_from_ra_dec` to convert a `str` passed as `name` into a single-element tuple when assigning it to `Star.names`, and also updates the docstring to indicate that a tuple or list of names is an acceptable value for the `name` parameter.

fix(time): Make Star.names iterable in skyfield_star_from_ra_dec

---

caput/tests/test_time.py
caput/time.py

This adds six methods to `caput.time.Observer` to calculate (solar/lunar) (transits/risings/settings).
These functions are originally from `ch_util.ephemeris` where they originally worked only on the `chime` `Observer`.  They've since been enhanced to use any `Observer`, so there's no reason now not to have them in the `Observer` object directly.
There is one major change to these functions from what was in `ch_util.ephemeris`:  instead of a `diameter` of 0.6 degrees = 36 arcminutes, these methods now use a `diameter` of 100 arcminutes.
This means these functions now compute astronomical sun/moon rise/set, which is conventionally taken to occur when the centre of the sun/moon is 50 arcminutes below the horizon.
The 50 arcminute number comes from a solar/lunar radius of 16 arcminutes plus …

feat(time): Solar/lunar ephemerides

---

caput/memh5.py

This PR makes the `shared` argument in `MemDiskGroup` actually share the `MemDataset` object and not just the underlying data array. Based on the idea of shared datasets being maintained through operations such as redistribution, axis downselection is not allowed for shared datasets.
It's important to note that the __default__ behaviour of `memh5.deep_group_copy` is (and has been since inception) to only make a _shallow_ copy of the `MemDataset` - i.e., the underlying array is actually shared. It doesn't matter when using this method to copy from disk -> memory or memory-> disk, but it does have implications when copying memory -> memory. This _probably_ shouldn't be the default behaviour, but we would have to be extremely careful if making any changes to avoid breaking anything.  
I've …

fix(memh5): fix a bug where shared datasets weren't actually shared

---

caput/cache.py

This is only used in a couple of places, so there will be separate PRs to fix that

Remove deprecated cached_property in favour of functools.cached_property

---

caput/pipeline.py
caput/tests/conftest.py
caput/tests/test_pipeline.py

- test(pipeline): ensure multiple output pipeline tasks are supported
- fix(pipeline): pipeline tasks can return multiple outputs to unpack

Pipeline tasks can return multiple outputs to unpack

---

caput/pipeline.py
tests/conftest.py
tests/test_pipeline.py

Add two features mentioned in #19
1. Add an interactive pipeline mode by creating a generator object which yields after each pipeline iteration
2. Add a task breakpoint parameter which, when triggered, causes the pipeline to stop and drop into `pdb` for debugging
Lingering questions:
- When a task has a breakpoint, breakpoint is triggered each time the task is called. Should it only happen once?
Also add tests for normal and interactive pipeline operation.
I'm open to suggestions for alternative ways to implement this.

Interactive pipeline debugging

---

caput/mpiarray.py

The pipeline runner is built as a generator and uses `StopIteration` to signal that it's done. This PR fixes a bug where a ufunc could be called with only numpy array inputs but `out=<mpiarray.MPIArray>`.

Fix inadvertent `StopIteration` in MPIArray which triggers the pipeline to end

---

.github/workflows/main.yml
caput/memh5.py
caput/mpiarray.py
caput/time.py
caput/weighted_median.pyx
pyproject.toml
tests/test_time.py

- compiles against numpy >= 2.0.0rc1
- calls `np.import_array()` in `weighted_median` to include required headers
- replaces deprecated `datetime.datetime.utcfromtimestamp` with `datetime.datetime.fromtimestamp(..., datetime.timezone.utc)`
- Uses legacy numpy print options - in numpy 2, numpy scalars are printed with type information, i.e. `np.float64(3.0)` instead of `3.0`. This breaks doctests.

Numpy 2.0 support

---

caput/memh5.py
caput/mpiarray.py

- The previous implementation of `newbyteorder` is deprecated in numpy 2.0. This change is compatible with nump 1.xx and numpy 2.x
- Minor doctest changes to handle new numpy scalar printing while maintaining compatibility with numpy 1.xx
- These are slightly annoying but I'm not really sure how else to maintain compatibility

Fix deprecated 'newbyteorder' and doctests

---

.gitignore
caput/config.py
caput/memh5.py
caput/mpiarray.py

The check `Ellipsis not in slobj` fails if there is a `np.ndarray` in slobj, which ends up checking each object in the tuple **and** each item in the `np.ndarray`, and thus ends up failing with `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. This change just checks each object in `slobj`, which seems to work.
Also Ruff.

Fix mpiarray global_slice Ellipsis check

---

caput/truncate.pyx
tests/test_truncate.py

Negative values would end up trying to truncate against negative error, which would always return `-0.0`. This makes sure that the error value is positive.

Properly propagate error in `bit_truncate_relative`

---

caput/pipeline.py

Required to run tasks which take multiple inputs in the case where we want both input to be the same

Pass the same key object to task with multiple process arguments

---

pyproject.toml

Zarr version 3.0 has a lot of breaking changes (see [here](https://zarr.readthedocs.io/en/stable/user-guide/v3_migration.html)). We should eventually updated `memh5` to address these changes, but for now I'm just pinning the version to less than 3.

Require zarr < 3

---

caput/fileformats.py
tests/test_memh5.py

Do not check against H5Filter if H5Filter is None.

fix(fileformats): fix compression check

---

caput/fftw.py
caput/memh5.py
caput/tod.py
pyproject.toml

There's a bug in `pyfftw` which seems to cause some sort of namespace issues with `numpy`. It seems like importing `pyfftw` before `numpy` fixes the issue, but this is environment-wide (i.e., it probably won't work in complex pipeline code where numpy is usually one of the first imports). However, I don't see any issue in at least slightly improving peoples chances of having it work.
This bug seems to still exist in the most recent version of `pyfftw`, so hopefully it gets fixed at some point.
Also, some fixes for ruff.

Import pyfftw before numpy

---

caput/config.py
caput/pipeline.py
pyproject.toml

This will be helpful when modifying old tasks.
I've also added a feature to the pipeline base task to add a debug log entry if a task returns the same object as one of the inputs, which suggests that it could have been modified in place. This is mostly for my own use if I'm trying to review weird behaviour in a pipeline config, but I think it's helpful.
There's something broken in the tests from a very recent release of `numcodecs` (https://numcodecs.readthedocs.io/en/stable/release.html#removals). 
There's already an open PR in `zarr` to address it, so I'm just going to leave this PR until that gets merged, because I don't want to have to pin `numcodecs` ourselves. Update: this still wasn't working properly with python 3.13, so I've just pinned `numcodecs`. I think we'll have to keep it …

Add a flag to deprecate config properties

---

caput/__init__.py
caput/coordinates/__init__.py
caput/fft/__init__.py
caput/fft/_scipy_fft.py
caput/fft/fftw.py
tests/test_fft.py

I want an easy way for users to access faster FFTs than what's provided by `numpy.fft` (which is quite slow). I had previously tried to do that with the `fftw` module, which is faster than `numpy/scipy`, but it ended up being finicky and has some annoying bugs. `fftw` is now accessed as a submodule of the `fft` submodule.
At the moment, the main `fft` module just re-exports `scipy.fft` with multiple workers set by default (`scipy` uses `pocketfft` as a backend, so I actually change the number of workers there). A full benchmark would probably be useful, but I've found that the overhead of using multiple workers is nullified quite quickly by the performance gained as arrays grow in size.
Going forward, I want to see if I can find some other, faster options. It should be reasonable to use …

Make a `fft` module, which contains the existing `fftw` module

---

caput/mpiutil.py
caput/scripts/runner.py

I'm planning to rework this a bit so we don't have these hard-coded cluster options, but this is just a quick fix for now

Include 'fir' in pipeline cluster options

---

caput/fileformats.py
caput/memh5.py
tests/test_memh5_parallel.py

As discussed in #303, it looks like the parallel compression issues with HDF5 are resolved since 1.13.1. 
This PR removes the code that forcibly disabled parallel compression, so writing parallel HDF5 should now behave the same way as writing parallel `zarr`. It also fixes a test that assumed that compression would always be disabled for hdf5 files.

Re-enable parallel compression for hdf5 files
